name: expert_properties
description: A new Flutter application.


publish_to:



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.0
  intl: ^0.16.1
  carousel_pro: ^1.0.0
  url_launcher: ^4.1.0
  foldable_sidebar: ^1.0.0
  connectivity: ^0.4.5+1
  shared_preferences: ^0.5.3+4
  dropdownfield: 1.0.0
  intro_slider: ^2.2.8
  simple_animations: ^1.3.4
  curved_navigation_bar: ^0.1.26
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For  details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
